source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'SwifTumblr_Example' do
  pod "SwifTumblr", :path => "../"
end

target 'SwifTumblr_Tests' do
  pod "SwifTumblr", :path => "../"
end

