language: swift
osx_image: xcode9
xcode_workspace: Example/SwifTumblr.xcworkspace
xcode_scheme: SwifTumblr-Example
xcode_sdk: iphonesimulator11.0
podfile: Example/Podfile
before_install:
    - gem update cocoapods
    - pod repo update
before_script:
    - brew unlink xctool
    - brew update || brew update
    - brew install xctool
script: xcodebuild -workspace Example/SwifTumblr.xcworkspace -scheme SwifTumblr-Example -sdk iphonesimulator11.0 -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.0' build test

